### ISSUE TITLE
plans for supporting notifications (sr_event_notif_*)?

### ISSUE THREAD

**Issue by nicolasmorini** [sysrepo/sysrepo-python#10]
Hi! Are there any plans to further develop these bindings to include the currently missing features? (I am particularly interested in the sr_event_notif_* at the moment).

If so, what is the expected time-frame for the changes to be available? If not, would you accept a pull-request adding support for notifications? (I do not have the time to work on this now, but I could spare some hours in the near future).

**Comment by rjarry** [comment]
Hi Nicolas,

I do not have time to work on new features at the moment. However, I'll gladly accept pull requests.

Thanks.

**Comment by rjarry** [comment]
@ishidawataru 

This looks ok at first sight. This would need unit tests obviously.

Can you please submit a PR? If you do not have additional time to work on this, maybe nicolas can use it as a starting point.

Thanks.

**Comment by ishidawataru** [comment]
@rjarry I opened a PR. I'd appreciate it if Nicolas can spend some time to make this mergeable.

**Comment by nicolasmorini** [comment]
Hi @rjarry and @ishidawataru! Thanks for your replies! I will review the PR in the upcoming days and come back to you

**Comment by rjarry** [comment]
Fixed in #17
