### ISSUE TITLE
Compatibility with  Netopeer2/Sysrepo/Libnetconf2/Libyang Current Versions

### ISSUE THREAD

**Issue by IkaroB** [sysrepo/sysrepo-python#12]
Hi,

I`d like to know if there is any version of this or other similar project that is compatible with netopeer2-v2.0.0 and its dependencies.
As far as I can tell, this one is not compatible with versions >= 2.x.x , right?

**Comment by rjarry** [comment]
Hi, you are correct. The 2.x support is planned before the end of the year.

**Comment by feelqah** [comment]
> Hi, you are correct. The 2.x support is planned before the end of the year.

Hi Robin,
any updates on the 2.x support?

**Comment by rjarry** [comment]
Hi,

sorry, I still haven't started working on this. Other projects (both work and personal) came first. There is a pending pull request for libyang 2 support https://github.com/CESNET/libyang-python/pull/28 which is a requirement for sysrepo 2. I need to integrate and validate it before starting the sysrepo part.

I would appreciate some help if you can spare the time :)

**Comment by ljyfree** [comment]
any progress?

**Comment by pwang111** [comment]
We are also waiting for the support of 2.x. sysrepo-python becomes a vital part of our combined NE architecture. Any expected time window for the release please? Thank you.

**Comment by jeanseb6wind** [comment]
Hello,
I'm currently working on it but I can't tell you exactly how much time it will take.

**Comment by tarkesh** [comment]
@jeanseb6wind  thanks for the update. Do you have an alpha/beta version you can push into a branch that i can try it out? or help fix any bugs? Thank you.

**Comment by rjarry** [comment]
Hi all, the latest releases should fix this issue:

https://pypi.org/project/libyang/2.1.0/
https://pypi.org/project/sysrepo/1.0.0/

Thanks again for your patience.
