### ISSUE TITLE
sysrepo rpc not working with "application_async.py"

### ISSUE THREAD

**Issue by sjd-xlnx** [sysrepo/sysrepo-python#14]
I'm using the "sysrepo-example" yang module to experiment with these Python sysrepo bindings.

I am sending the following rpc using netopeer2-cli...
```
<poweroff xmlns="http://sysrepo-example.com/sysrepo-example">
	<behaviour>success</behaviour>
</poweroff>
```

When using the "application.py" this works as expected, and I see the following on the netopeer2-cli...
```
> user-rpc --content example-rpc.xml
DATA
<message xmlns="http://sysrepo-example.com/sysrepo-example">bye bye</message>
```

But when I use the "application_async.py", it does not work properly. On the netopeer2-cli I see...
```
> user-rpc --content example-rpc.xml
OK
```
And on the console for application_async.py, I see...
```
INFO] application: Processing "/sysrepo-example:poweroff" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[INFO] application: Shelved processing of "rpc" event with ID 1 priority 0.

========================
RPC call: /sysrepo-example:poweroff
params: {'behaviour': 'success'}
returning {'poweroff': {'message': 'bye bye'}}
---------------

[INFO] application: Processing "/sysrepo-example:poweroff" "rpc" event with ID 1 priority 0 (remaining 1 subscribers).
[WARNING] application: /sysrepo-example:poweroff: skipping unknown element 'poweroff'
[INFO] application: Successful processing of "rpc" event with ID 1 priority 0 (remaining 0 subscribers).
```

So, it seems the RPC message is seen and handled by the call-back, but something goes wrong, and it fails to get processed correctly.

Any ideas?

**Comment by sjd-xlnx** [comment]
This seems to have been a mistake in the example/application_async.py

In function "async def poweroff()"...
```
<     out = {"poweroff": {"message": "bye bye"}} # Doesn't work
>     out = {"message": "bye bye"} # Works
```

**Comment by rjarry** [comment]
Hi sorry not to have replied earlier.

Indeed the example is incorrect. I will fix this asap.
