### ISSUE TITLE
Question: asyncio mode

### ISSUE THREAD

**Issue by chaichairiko** [sysrepo/sysrepo-python#3]
Hi,
Looking at the examples, I see that every callback method in asyncio mode ends with `await asyncio.sleep(0)`.
Is this a must? doesn't the event loop "see" that the task ended?

Regards,
Chai

**Comment by rjarry** [comment]
Hi,

This is only to show that the `async` methods can indeed "call" `async` functions. Obviously, in real world cases, you would actually await something (subprocess command termination, read/write from/to non-blocking socket, etc.).

If you don't need to `await` anything in the callbacks, it is better to use regular (non `async`) functions then.

Note that you can also use `asyncio_register=True` with regular functions. The only difference is that `libsysrepo.so` does not create a thread and that the `asyncio` event loop is responsible of monitoring the subscription event pipe file descriptor and calling your registered callback.

https://github.com/sysrepo/sysrepo-python/blob/v0.1.3/sysrepo/subscription.py#L85-L87
https://github.com/sysrepo/sysrepo-python/blob/v0.1.3/sysrepo/subscription.py#L118-L122

When `asyncio_register=True` and the callback is an `async` function, it is scheduled for execution in `asyncio` event loop and `SR_ERR_CALLBACK_SHELVE` is returned to `libsysrepo.so`:

https://github.com/sysrepo/sysrepo-python/blob/v0.1.3/sysrepo/subscription.py#L235-L236

**Comment by chaichairiko** [comment]
Thanks for the detailed answer!
