### ISSUE TITLE
Compatibility with 2.x versions of sysrepo and libyang

### ISSUE THREAD

**Issue by sjd-xlnx** [sysrepo/sysrepo-python#40]
Hi,

Just seeking clarification about https://github.com/sysrepo/sysrepo-python/issues/12, which was closed with the comment from @rjarry 
that "Hi all, the latest releases should fix this issue". Is this the case? The README on the main git page and PyPI still says...

"For now, only the 1.x versions of [sysrepo](https://github.com/sysrepo/sysrepo/tree/libyang1) and [libyang](https://github.com/CESNET/libyang/tree/libyang1) are supported."

I'm in the middle of trying to upgrade, but wasn't sure if it was all working correctly yet due to above comment.

Thanks and kind regards.

**Comment by rjarry** [comment]
Hi Steven,

I completely forgot to update that disclaimer.

The 2.x versions of the python bindings are only compatible with libyang 2.x and sysrepo 2.x.

I will update the README accordingly.

**Comment by sjd-xlnx** [comment]
Thanks Robin. Super quick! 🥇
