### ISSUE TITLE
Question: How to find session id of client sending a request

### ISSUE THREAD

**Issue by sjd-xlnx** [sysrepo/sysrepo-python#41]
Hello,

I am developing code for NETCONF server using the Python Sysrepo binding. I have the basics working, i.e. callbacks for get/edit/rpcs and code for sending notifications. But, one thing that puzzles me, is if there is anyway to tell who sent (i.e. which NETCONF client (session-id?)) a particular message to the server that my code processes.

For example, a NETCONF client sends a "reset RPC" to the server. I have code that can handle it, but it would nice to know the session-id of the sender. Presumably the netopeer2-server knows this, but doesn't seem like this information is available using sysrepo's APIs.

Any suggestions?

Thanks in advance.

**Comment by rjarry** [comment]
Glad you got that sorted, sorry not to have replied earlier :+1:
