### ISSUE TITLE
Failed to parse data tree: Unexpected RPC element

### ISSUE THREAD

**Issue by Villiere-Lucas** [sysrepo/sysrepo-python#46]
Hello,

I'm a student working with sysrepo-python and I'm trying to implement the small example from the folder examples inside the repository.

So when I'm trying to run the application using the sysrepocfg from C library everything works fine and I get a respond in the application.py.

````
$ sysrepocfg -d running -f json --rpc=tes.json
{
  "sysrepo-example:poweroff": {
    "message": "bye bye"
  }
}



$ python3 application.py 

========================
RPC call: /sysrepo-example:poweroff
params: {'behaviour': 'success'}
returning {'message': 'bye bye'}
---------------

````

But when I'm trying to do the same thing with the sysrepocfg.py, I get an error :

First I run this command:
`$ echo '{"sysrepo-example:poweroff": {"behaviour": "success" }}' | python3 sysrepocfg.py -d running -f json -R`

And I get this error:

````Traceback (most recent call last):
  File "/home/lucas/PycharmProjects/sysrepo-python/examples/sysrepocfg.py", line 133, in <module>
    sys.exit(main())

  File "/home/lucas/PycharmProjects/sysrepo-python/examples/sysrepocfg.py", line 112, in main
    rpc_input = ctx.parse_data_mem(

  File "/home/lucas/.local/lib/python3.10/site-packages/libyang/context.py", line 394, in parse_data_mem
    return self.parse_data(

  File "/home/lucas/.local/lib/python3.10/site-packages/libyang/context.py", line 374, in parse_data
    raise self.error("failed to parse data tree")

libyang.util.LibyangError: failed to parse data tree: Unexpected RPC element "poweroff".
````
I don't understand what I'm doing wrong could you maybe help me to clarify that point ?

Thank you!

**Comment by rjarry** [comment]
Hi,

what are the contents of the `tes.json` file?

I assume that the same application.py is running when you are trying to run the rpc.

**Comment by Villiere-Lucas** [comment]
Hello,

the `tes.json` is exaclty the same content as the  `echo '{"sysrepo-example:poweroff": {"behaviour": "success" }}'`

So like this : 

```
{
  "sysrepo-example:poweroff": {
    "behaviour": "success"
  }
}
```

Yes the same `application.py` is running when I'm trying to run the rpc.
