### ISSUE TITLE
Replace datastore using --copy-from

### ISSUE THREAD

**Issue by tbsuht** [sysrepo/sysrepo-python#55]
Hi,

am I right, that something like 
`./bin/sysrepocfg --copy-from candidate --datastore running` 
is not implemented in the python wrapper?
Is there an easy way to achieve the same? Is it `get_data` + `replace_config`?

**Comment by tbsuht** [comment]
@rjarry Wow, that was fast. Thanks a lot!

**Comment by rjarry** [comment]
Cheers :)
