### ISSUE TITLE
Creating a python application plugin

### ISSUE THREAD

**Issue by mdivyamohan** [sysrepo/sysrepo-python#8]
In example [code](https://github.com/sysrepo/sysrepo/blob/master/examples/plugin/oven.c) of sysrepo plugin, `
sr_plugin_init_cb` and `sr_plugin_cleanup_cb` functions are implemented to run as a plugin.

Is it possible to write a plugin in python similarly? Or only appliction deamon can be implemented in python?

**Comment by rjarry** [comment]
Hi, sorry not to have replied earlier, I missed the email notification.

I don't think sysrepo plugins can be implemented as any other thing than a `.so` file (same as libyang plugins). You "may" be able to create a `.so` file that uses `libpython.so` to do the work in python but it will be much simpler to write a daemon application directly in python.
